### PR TITLE
[Unfolder] fix element access on FC0.21

### LINKED ISSUE #465: [newUnfolder] "Part.Solid" object has no attribute "findSubShape"
### Describe your issue

After changes #456 the new unfolding system stopped working in version 0.21 :(
@alexneufeld

```
Using V2 unfolding system
Traceback (most recent call last):
  File "/home/***/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalUnfoldCmd.py", line 271, in execute
    shape, sketches = self.newUnfolder(fp)
  File "/home/***/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalUnfoldCmd.py", line 219, in newUnfolder
    sel_face, unfolded_shape, bend_lines, root_normal = SheetMetalNewUnfolder.getUnfold(
  File "/home/***/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalNewUnfolder.py", line 1307, in getUnfold
    root_face_index = shp.findSubShape(subshape)[1] - 1
<class 'AttributeError'>: 'Part.Solid' object has no attribute 'findSubShape'
Recompute failed!
```

### FreeCAD version info + SheetMetal WB version

```shell
OS: Ubuntu 22.04.5 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * fasteners 0.5.37
  * Assembly4 0.50.16-dev
  * Plot 2024.11.26
  * CfdOF 1.29.6
  * sheetmetal 0.7.5
  * addFC 1.2.4
```

### Put here any screenshots or videos (optional)

[smFile.zip](https://github.com/user-attachments/files/18632820/smFile.zip)

### PR DESCRIPTION
**Pull request by alexneufeld**
fixes #465

@GS90 please test

### CODE REVIEW

**Comment by GS90** [comment]
```
Using V2 unfolding system
Traceback (most recent call last):
  File "/home/**/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalUnfoldCmd.py", line 271, in execute
    shape, sketches = self.newUnfolder(fp)
  File "/home/**/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalUnfoldCmd.py", line 219, in newUnfolder
    sel_face, unfolded_shape, bend_lines, root_normal = SheetMetalNewUnfolder.getUnfold(
  File "/home/**/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalNewUnfolder.py", line 1326, in getUnfold
    sketch_wirelist = Edge2DCleanup.clean_and_structure_geometry(sketch_lines)
  File "/home/**/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalNewUnfolder.py", line 956, in clean_and_structure_geometry
    intermediate_result2 = Edge2DCleanup.fix_coincidence(intermediate_result1, fuzz)
  File "/home/**/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalNewUnfolder.py", line 867, in fix_coincidence
    list_of_lists_of_edges = Part.sortEdges(edgelist, fuzzvalue)
<class 'Part.OCCError'>: list of edges expected
Recompute failed!
```

**Comment by GS90** [comment]
Without passing "fuzzvalue" the result with "SeparateSketchLayers" is incorrect :(
The outer contour is defined as the internal.

image

**Comment by alexneufeld** [comment]
looks like https://github.com/FreeCAD/FreeCAD/commit/df9c8f655659d89a5cafc56c48aeddad07554b41 didn't make it into 0.21 :cry: 

The incorrect outer contour is an OCC limitation, the unfolded solid's `OuterWire` just returns the wrong thing

re-implimenting https://github.com/FreeCAD/FreeCAD/blob/df9c8f655659d89a5cafc56c48aeddad07554b41/src/Mod/Part/App/AppPartPy.cpp#L156 as a polyfill in python isn't realistic, it would be very slow


I strongly recommend using FreeCAD version 1.0 if you want to use the new unfolder. Otherwise, consider reverting to the old unfolder in the sheetmetal preferences.

**Comment by GS90** [comment]
>  The outer contour is defined as the internal.

I have tested my parts and it very much depends on the chosen face to unfold.

I would be happy to use FreeCAD 1.0 and higher, but sheet metal has other problems there :(

Overall, I think the problem #465 has been fixed.
Thank you very much!

**Comment by shaise** [comment]
@alexneufeld , Thanks!
@GS90 , What are the main problems of sheetmetal and 1.0?

**Comment by GS90** [comment]
@shaise
Errors in elements after bending (mainly Fillet and Chamfer).
#342 and #343

**Comment by shaise** [comment]
So basically toponaming creating issues. Yes I get that.
