### ISSUE TITLE
[newUnfolder] "Part.Solid" object has no attribute "findSubShape"

### ISSUE THREAD

**Issue by GS90** [shaise/FreeCAD_SheetMetal#465]
### Describe your issue

After changes #456 the new unfolding system stopped working in version 0.21 :(
@alexneufeld

```
Using V2 unfolding system
Traceback (most recent call last):
  File "/home/***/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalUnfoldCmd.py", line 271, in execute
    shape, sketches = self.newUnfolder(fp)
  File "/home/***/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalUnfoldCmd.py", line 219, in newUnfolder
    sel_face, unfolded_shape, bend_lines, root_normal = SheetMetalNewUnfolder.getUnfold(
  File "/home/***/.local/share/FreeCAD/Mod/sheetmetal/./SheetMetalNewUnfolder.py", line 1307, in getUnfold
    root_face_index = shp.findSubShape(subshape)[1] - 1
<class 'AttributeError'>: 'Part.Solid' object has no attribute 'findSubShape'
Recompute failed!
```

### FreeCAD version info + SheetMetal WB version

```shell
OS: Ubuntu 22.04.5 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * fasteners 0.5.37
  * Assembly4 0.50.16-dev
  * Plot 2024.11.26
  * CfdOF 1.29.6
  * sheetmetal 0.7.5
  * addFC 1.2.4
```

### Put here any screenshots or videos (optional)

[smFile.zip](https://github.com/user-attachments/files/18632820/smFile.zip)
